name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run markdown lint
      run: |
        npm i lint-md-cli,
        lint-md README.md
